### ISSUE TITLE
RandomForest implementation

### ISSUE THREAD

**Issue by seventharchangel** [frostyandy2k/pmml2js#1]
Could you implement a random forest solution as well?

Ramdom forest basically rely on decision trees. They consists of multiple decision trees, each used to predict the class variable. Using majority vote, the most frequent prediction is returned as result to the random forest.

**Comment by frostyandy2k** [comment]
Will do.
Will also try to speed things up with web workers.

**Comment by frostyandy2k** [comment]
Thanks for the contribution (randomforest_engine.js).
Web workers will have to wait for now.

**Comment by frostyandy2k** [comment]
Closing this issue and opening a new one for web workers
