### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by painkkiller** [frostyandy2k/pmml2js#4]
Didn't get the idea, I have a file with XML pmml model in it. How I can convert it to js with you library? Please provide any example code.

**Comment by painkkiller** [comment]
Sorry I misunderstood documentation, I supposed It works as node.js module but it isn't

**Comment by frostyandy2k** [comment]
Hi, the library was meant to work in the browser. It uses the browsers XML API. If you find XML libraries with similar functionality, like the ones used in the browser, you can use it server side with node. 

Feel free to create a pull request if you do!

**Comment by painkkiller** [comment]
Ok thanks for quick responce!

**Comment by frostyandy2k** [comment]
Created new issue with a task to create a node module: #5 

Closing this one.
